(function(){
'use strict';
var root=document.getElementById('bb-date-converter');if(!root||!window.BBNepaliDate)return;var D=window.BBNepaliDate;var $=function(id){return root.querySelector('#'+id);};var MONTHS_AD=['January','February','March','April','May','June','July','August','September','October','November','December'];
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}function pad(n){return String(n).padStart(2,'0');}
function resultBox(main,sub,np){return '<div class="bb-dc-result-main">'+esc(main)+'</div><div class="bb-dc-result-sub">'+esc(sub)+'</div>'+(np?'<div class="bb-dc-result-np">'+esc(np)+'</div>':'');}function errorBox(msg){return '<div class="bb-dc-error" role="alert">'+esc(msg)+'</div>';}
function fillYears(){var y=$('bb-dc-bs-year');y.innerHTML='';for(var n=D.BS_MAX;n>=D.BS_MIN;n--)y.add(new Option(n,n));}function fillMonths(){var m=$('bb-dc-bs-month');m.innerHTML='';D.MONTHS_EN.forEach(function(name,i){m.add(new Option((i+1)+' — '+name,i+1));});}
function fillDays(){var y=Number($('bb-dc-bs-year').value),m=Number($('bb-dc-bs-month').value),max=D.bsMonthDays(y,m),current=Number($('bb-dc-bs-day').value)||1,d=$('bb-dc-bs-day');d.innerHTML='';for(var n=1;n<=max;n++)d.add(new Option(n,n));d.value=String(Math.min(current,max));}
function convertAd(){try{var raw=$('bb-dc-ad').value;if(!raw)throw new Error('Select a Gregorian date.');var p=raw.split('-').map(Number),x=D.adToBs(p[0],p[1],p[2]);$('bb-dc-ad-result').innerHTML='<button id="bb-dc-ad-copy" class="bb-dc-copy" type="button">Copy</button>'+resultBox(x.iso+' BS',x.monthName+' '+x.date+', '+x.year+' · '+x.day,D.toNepaliDigits(x.year)+' '+x.monthNameNp+' '+D.toNepaliDigits(x.date)+' · '+x.dayNp);$('bb-dc-ad-copy').addEventListener('click',function(){copyResult('bb-dc-ad-result',this);});}catch(e){$('bb-dc-ad-result').innerHTML=errorBox(e.message||'Unable to convert this date.');}}
function convertBs(){try{var y=Number($('bb-dc-bs-year').value),m=Number($('bb-dc-bs-month').value),d=Number($('bb-dc-bs-day').value),x=D.bsToAd(y,m,d);$('bb-dc-bs-result').innerHTML='<button id="bb-dc-bs-copy" class="bb-dc-copy" type="button">Copy</button>'+resultBox(x.iso+' AD',MONTHS_AD[x.month-1]+' '+x.date+', '+x.year+' · '+x.day,D.toNepaliDigits(y)+' '+D.MONTHS_NP[m-1]+' '+D.toNepaliDigits(d));$('bb-dc-bs-copy').addEventListener('click',function(){copyResult('bb-dc-bs-result',this);});}catch(e){$('bb-dc-bs-result').innerHTML=errorBox(e.message||'Unable to convert this date.');}}
function setToday(){var now=new Date(),iso=now.getFullYear()+'-'+pad(now.getMonth()+1)+'-'+pad(now.getDate()),input=$('bb-dc-ad');if(iso>=input.min&&iso<=input.max){input.value=iso;convertAd();}}
function copyResult(id,btn){var text=$(id).innerText.replace('Copy','').trim();if(!text)return;function done(){var old=btn.textContent;btn.textContent='Copied';setTimeout(function(){btn.textContent=old;},1000);}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(done).catch(function(){});}else{var t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();done();}}
fillYears();fillMonths();$('bb-dc-bs-year').value='2083';$('bb-dc-bs-month').value='5';fillDays();$('bb-dc-bs-day').value='7';$('bb-dc-bs-year').addEventListener('change',fillDays);$('bb-dc-bs-month').addEventListener('change',fillDays);$('bb-dc-ad-btn').addEventListener('click',convertAd);$('bb-dc-bs-btn').addEventListener('click',convertBs);$('bb-dc-today').addEventListener('click',setToday);$('bb-dc-ad').min='1918-04-13';$('bb-dc-ad').max=D.maxAdIso();setToday();convertBs();
})();